### ISSUE TITLE
Getting an AttributeError if I did not provide any subcommand

### ISSUE THREAD

**Issue by bloodpet** [JeNeSuisPasDave/authenticator#3]
When I run with just:
`$ authenticator`

I get this output:

> Traceback (most recent call last):
  File "/usr/local/bin/authenticator", line 11, in <module>
    sys.exit(authenticator_command())
  File "/usr/local/lib/python3.5/dist-packages/authenticator/cli.py", line 1241, in authenticator_command
    m.execute()
  File "/usr/local/lib/python3.5/dist-packages/authenticator/cli.py", line 1198, in execute
    if self.args.subcmd not in (
AttributeError: 'Namespace' object has no attribute 'subcmd'

It would be nice to see the usage instead.

**Comment by JeNeSuisPasDave** [comment]
I hope to fix this before end of 2019. Sorry, but I didn't notice this issue before today. :-(

**Comment by 4-0-4-notfound** [comment]
same here

**Comment by bloodpet** [comment]
@JeNeSuisPasDave you could merge the [PR](https://github.com/JeNeSuisPasDave/authenticator/pull/4/files) if that's acceptable. It's a decent fix :)
